import React from 'react'

function studentdata() {
  return (
    <table className="studentData">
      <tr className="studenthead">
        <th>First Name</th>
        <th>Second Name</th>
        <th>My Favorite Programming Language</th>
      </tr>
      <tr>
        <td>Oluwatimilehin</td>
        <td>Shodiya</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>Chidera</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Samuel</td>
        <td>Odinaka</td>
        <td>C#</td>
      </tr>
      <tr>
        <td>Favor</td>
        <td>Orji</td>
        <td>GoLang</td>
      </tr>
      <tr>
        <td>Grace</td>
        <td>Smith</td>
        <td>C++</td>
      </tr>
      <tr>
        <td>Mark</td>
        <td>Zuck</td>
        <td>PHP</td>
      </tr>
      <tr>
        <td>Will</td>
        <td>Gluck</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Faith</td>
        <td>Balogun</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>Chidera</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>Chidera</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>Chidera</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>Chidera</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>Chidera</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>Chidera</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>Chidera</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>Chidera</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>Chidera</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>Chidera</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>Chidera</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>Chidera</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>Chidera</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>Chidera</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>Chidera</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>Chidera</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>Chidera</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>Chidera</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>Chidera</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>Chidera</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>Chidera</td>
        <td>Javascript</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>Chidera</td>
        <td>Javascript</td>
      </tr>
    </table>
  )
}

export default studentdata
